name: prayerrise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Prayer & Location
  adhan: ^2.0.0+1
  geolocator: ^14.0.2
  flutter_qiblah: ^3.2.0

  # Utilities
  intl: ^0.18.1
  http: ^1.1.0
  timezone: ^0.9.4

  # Storage
  shared_preferences: ^2.2.2

  # Notifications
  flutter_local_notifications: ^16.3.3

  # Audio
  audioplayers: ^6.7.0

  # Web
  web: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/audio/adhan.mp3

  fonts:
    - family: QuranFont
      fonts:
        - asset: lib/assets/fonts/Amiri-Regular.ttf
